name: Create Release on Tag

on:
  push:
    tags:
      - 'v*.*.*'   # Запускається при пуші тегів формату v1.0.0 - vX.X.X

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            ## Автоматично створений реліз для тегу `${{ github.ref_name }}`.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
